import { lowerCase } from "../utils/helpers";

interface Country { code: string; timezone: string; name: string }

const countries: Country[] = [
    { code: "CI", timezone: "Africa/Abidjan", name: "Ivory Coast" },
    { code: "GH", timezone: "Africa/Accra", name: "Ghana" },
    { code: "ET", timezone: "Africa/Addis_Ababa", name: "Ethiopia" },
    { code: "DZ", timezone: "Africa/Algiers", name: "Algeria" },
    { code: "ER", timezone: "Africa/Asmara", name: "Eritrea" },
    { code: "ER", timezone: "Africa/Asmera", name: "Eritrea" },
    { code: "ML", timezone: "Africa/Bamako", name: "Mali" },
    { code: "CF", timezone: "Africa/Bangui", name: "Central African Republic" },
    { code: "GM", timezone: "Africa/Banjul", name: "Gambia" },
    { code: "GW", timezone: "Africa/Bissau", name: "Guinea-Bissau" },
    { code: "MW", timezone: "Africa/Blantyre", name: "Malawi" },
    { code: "CG", timezone: "Africa/Brazzaville", name: "Republic of the Congo" },
    { code: "BI", timezone: "Africa/Bujumbura", name: "Burundi" },
    { code: "EG", timezone: "Africa/Cairo", name: "Egypt" },
    { code: "MA", timezone: "Africa/Casablanca", name: "Morocco" },
    { code: "ES", timezone: "Africa/Ceuta", name: "Spain" },
    { code: "GN", timezone: "Africa/Conakry", name: "Guinea" },
    { code: "SN", timezone: "Africa/Dakar", name: "Senegal" },
    { code: "TZ", timezone: "Africa/Dar_es_Salaam", name: "Tanzania" },
    { code: "DJ", timezone: "Africa/Djibouti", name: "Djibouti" },
    { code: "CM", timezone: "Africa/Douala", name: "Cameroon" },
    { code: "EH", timezone: "Africa/El_Aaiun", name: "Western Sahara" },
    { code: "SL", timezone: "Africa/Freetown", name: "Sierra Leone" },
    { code: "BW", timezone: "Africa/Gaborone", name: "Botswana" },
    { code: "ZW", timezone: "Africa/Harare", name: "Zimbabwe" },
    { code: "ZA", timezone: "Africa/Johannesburg", name: "South Africa" },
    { code: "SS", timezone: "Africa/Juba", name: "South Sudan" },
    { code: "UG", timezone: "Africa/Kampala", name: "Uganda" },
    { code: "SD", timezone: "Africa/Khartoum", name: "Sudan" },
    { code: "RW", timezone: "Africa/Kigali", name: "Rwanda" },
    { code: "CD", timezone: "Africa/Kinshasa", name: "Democratic Republic of the Congo" },
    { code: "NG", timezone: "Africa/Lagos", name: "Nigeria" },
    { code: "GA", timezone: "Africa/Libreville", name: "Gabon" },
    { code: "TG", timezone: "Africa/Lome", name: "Togo" },
    { code: "AO", timezone: "Africa/Luanda", name: "Angola" },
    { code: "CD", timezone: "Africa/Lubumbashi", name: "Democratic Republic of the Congo" },
    { code: "ZM", timezone: "Africa/Lusaka", name: "Zambia" },
    { code: "GQ", timezone: "Africa/Malabo", name: "Equatorial Guinea" },
    { code: "MZ", timezone: "Africa/Maputo", name: "Mozambique" },
    { code: "LS", timezone: "Africa/Maseru", name: "Lesotho" },
    { code: "SZ", timezone: "Africa/Mbabane", name: "Swaziland" },
    { code: "SO", timezone: "Africa/Mogadishu", name: "Somalia" },
    { code: "LR", timezone: "Africa/Monrovia", name: "Liberia" },
    { code: "KE", timezone: "Africa/Nairobi", name: "Kenya" },
    { code: "TD", timezone: "Africa/Ndjamena", name: "Chad" },
    { code: "NE", timezone: "Africa/Niamey", name: "Niger" },
    { code: "MR", timezone: "Africa/Nouakchott", name: "Mauritania" },
    { code: "BF", timezone: "Africa/Ouagadougou", name: "Burkina Faso" },
    { code: "BJ", timezone: "Africa/Porto-Novo", name: "Benin" },
    { code: "ST", timezone: "Africa/Sao_Tome", name: "Sao Tome and Principe" },
    { code: "ML", timezone: "Africa/Timbuktu", name: "Mali" },
    { code: "LY", timezone: "Africa/Tripoli", name: "Libya" },
    { code: "TN", timezone: "Africa/Tunis", name: "Tunisia" },
    { code: "NA", timezone: "Africa/Windhoek", name: "Namibia" },
    { code: "US", timezone: "America/Adak", name: "United States" },
    { code: "US", timezone: "America/Anchorage", name: "United States" },
    { code: "AI", timezone: "America/Anguilla", name: "Anguilla" },
    { code: "AG", timezone: "America/Antigua", name: "Antigua and Barbuda" },
    { code: "BR", timezone: "America/Araguaina", name: "Brazil" },
    { code: "AR", timezone: "America/Argentina/Buenos_Aires", name: "Argentina" },
    { code: "AR", timezone: "America/Argentina/Catamarca", name: "Argentina" },
    { code: "AR", timezone: "America/Argentina/ComodRivadavia", name: "Argentina" },
    { code: "AR", timezone: "America/Argentina/Cordoba", name: "Argentina" },
    { code: "AR", timezone: "America/Argentina/Jujuy", name: "Argentina" },
    { code: "AR", timezone: "America/Argentina/La_Rioja", name: "Argentina" },
    { code: "AR", timezone: "America/Argentina/Mendoza", name: "Argentina" },
    { code: "AR", timezone: "America/Argentina/Rio_Gallegos", name: "Argentina" },
    { code: "AR", timezone: "America/Argentina/Salta", name: "Argentina" },
    { code: "AR", timezone: "America/Argentina/San_Juan", name: "Argentina" },
    { code: "AR", timezone: "America/Argentina/San_Luis", name: "Argentina" },
    { code: "AR", timezone: "America/Argentina/Tucuman", name: "Argentina" },
    { code: "AR", timezone: "America/Argentina/Ushuaia", name: "Argentina" },
    { code: "AW", timezone: "America/Aruba", name: "Aruba" },
    { code: "PY", timezone: "America/Asuncion", name: "Paraguay" },
    { code: "CA", timezone: "America/Atikokan", name: "Canada" },
    { code: "US", timezone: "America/Atka", name: "United States" },
    { code: "BR", timezone: "America/Bahia", name: "Brazil" },
    { code: "MX", timezone: "America/Bahia_Banderas", name: "Mexico" },
    { code: "BB", timezone: "America/Barbados", name: "Barbados" },
    { code: "BR", timezone: "America/Belem", name: "Brazil" },
    { code: "BZ", timezone: "America/Belize", name: "Belize" },
    { code: "CA", timezone: "America/Blanc-Sablon", name: "Canada" },
    { code: "BR", timezone: "America/Boa_Vista", name: "Brazil" },
    { code: "CO", timezone: "America/Bogota", name: "Colombia" },
    { code: "US", timezone: "America/Boise", name: "United States" },
    { code: "AR", timezone: "America/Buenos_Aires", name: "Argentina" },
    { code: "CA", timezone: "America/Cambridge_Bay", name: "Canada" },
    { code: "BR", timezone: "America/Campo_Grande", name: "Brazil" },
    { code: "MX", timezone: "America/Cancun", name: "Mexico" },
    { code: "VE", timezone: "America/Caracas", name: "Venezuela" },
    { code: "AR", timezone: "America/Catamarca", name: "Argentina" },
    { code: "KY", timezone: "America/Cayman", name: "Cayman Islands" },
    { code: "US", timezone: "America/Chicago", name: "United States" },
    { code: "MX", timezone: "America/Chihuahua", name: "Mexico" },
    { code: "CA", timezone: "America/Coral_Harbour", name: "Canada" },
    { code: "AR", timezone: "America/Cordoba", name: "Argentina" },
    { code: "CR", timezone: "America/Costa_Rica", name: "Costa Rica" },
    { code: "CA", timezone: "America/Creston", name: "Canada" },
    { code: "BR", timezone: "America/Cuiaba", name: "Brazil" },
    { code: "CW", timezone: "America/Curacao", name: "Curacao" },
    { code: "GL", timezone: "America/Danmarkshavn", name: "Greenland" },
    { code: "CA", timezone: "America/Dawson", name: "Canada" },
    { code: "CA", timezone: "America/Dawson_Creek", name: "Canada" },
    { code: "US", timezone: "America/Denver", name: "United States" },
    { code: "US", timezone: "America/Detroit", name: "United States" },
    { code: "DM", timezone: "America/Dominica", name: "Dominica" },
    { code: "CA", timezone: "America/Edmonton", name: "Canada" },
    { code: "BR", timezone: "America/Eirunepe", name: "Brazil" },
    { code: "SV", timezone: "America/El_Salvador", name: "El Salvador" },
    { code: "MX", timezone: "America/Ensenada", name: "Mexico" },
    { code: "CA", timezone: "America/Fort_Nelson", name: "Canada" },
    { code: "US", timezone: "America/Fort_Wayne", name: "United States" },
    { code: "BR", timezone: "America/Fortaleza", name: "Brazil" },
    { code: "CA", timezone: "America/Glace_Bay", name: "Canada" },
    { code: "GL", timezone: "America/Godthab", name: "Greenland" },
    { code: "CA", timezone: "America/Goose_Bay", name: "Canada" },
    { code: "TC", timezone: "America/Grand_Turk", name: "Turks and Caicos Islands" },
    { code: "GD", timezone: "America/Grenada", name: "Grenada" },
    { code: "GP", timezone: "America/Guadeloupe", name: "Guadeloupe" },
    { code: "GT", timezone: "America/Guatemala", name: "Guatemala" },
    { code: "EC", timezone: "America/Guayaquil", name: "Ecuador" },
    { code: "GY", timezone: "America/Guyana", name: "Guyana" },
    { code: "CA", timezone: "America/Halifax", name: "Canada" },
    { code: "CU", timezone: "America/Havana", name: "Cuba" },
    { code: "MX", timezone: "America/Hermosillo", name: "Mexico" },
    { code: "US", timezone: "America/Indiana/Indianapolis", name: "United States" },
    { code: "US", timezone: "America/Indiana/Knox", name: "United States" },
    { code: "US", timezone: "America/Indiana/Marengo", name: "United States" },
    { code: "US", timezone: "America/Indiana/Petersburg", name: "United States" },
    { code: "US", timezone: "America/Indiana/Tell_City", name: "United States" },
    { code: "US", timezone: "America/Indiana/Vevay", name: "United States" },
    { code: "US", timezone: "America/Indiana/Vincennes", name: "United States" },
    { code: "US", timezone: "America/Indiana/Winamac", name: "United States" },
    { code: "US", timezone: "America/Indianapolis", name: "United States" },
    { code: "CA", timezone: "America/Inuvik", name: "Canada" },
    { code: "CA", timezone: "America/Iqaluit", name: "Canada" },
    { code: "JM", timezone: "America/Jamaica", name: "Jamaica" },
    { code: "AR", timezone: "America/Jujuy", name: "Argentina" },
    { code: "US", timezone: "America/Juneau", name: "United States" },
    { code: "US", timezone: "America/Kentucky/Louisville", name: "United States" },
    { code: "US", timezone: "America/Kentucky/Monticello", name: "United States" },
    { code: "US", timezone: "America/Knox_IN", name: "United States" },
    { code: "BO", timezone: "America/La_Paz", name: "Bolivia" },
    { code: "PE", timezone: "America/Lima", name: "Peru" },
    { code: "US", timezone: "America/Los_Angeles", name: "United States" },
    { code: "US", timezone: "America/Louisville", name: "United States" },
    { code: "SX", timezone: "America/Lower_Princes", name: "Sint Maarten" },
    { code: "BR", timezone: "America/Maceio", name: "Brazil" },
    { code: "NI", timezone: "America/Managua", name: "Nicaragua" },
    { code: "BR", timezone: "America/Manaus", name: "Brazil" },
    { code: "MF", timezone: "America/Marigot", name: "Saint Martin" },
    { code: "MQ", timezone: "America/Martinique", name: "Martinique" },
    { code: "MX", timezone: "America/Matamoros", name: "Mexico" },
    { code: "MX", timezone: "America/Mazatlan", name: "Mexico" },
    { code: "AR", timezone: "America/Mendoza", name: "Argentina" },
    { code: "US", timezone: "America/Menominee", name: "United States" },
    { code: "MX", timezone: "America/Merida", name: "Mexico" },
    { code: "US", timezone: "America/Metlakatla", name: "United States" },
    { code: "MX", timezone: "America/Mexico_City", name: "Mexico" },
    { code: "PM", timezone: "America/Miquelon", name: "Saint Pierre and Miquelon" },
    { code: "CA", timezone: "America/Moncton", name: "Canada" },
    { code: "MX", timezone: "America/Monterrey", name: "Mexico" },
    { code: "UY", timezone: "America/Montevideo", name: "Uruguay" },
    { code: "CA", timezone: "America/Montreal", name: "Canada" },
    { code: "MS", timezone: "America/Montserrat", name: "Montserrat" },
    { code: "BS", timezone: "America/Nassau", name: "Bahamas" },
    { code: "US", timezone: "America/New_York", name: "United States" },
    { code: "CA", timezone: "America/Nipigon", name: "Canada" },
    { code: "US", timezone: "America/Nome", name: "United States" },
    { code: "BR", timezone: "America/Noronha", name: "Brazil" },
    { code: "US", timezone: "America/North_Dakota/Beulah", name: "United States" },
    { code: "US", timezone: "America/North_Dakota/Center", name: "United States" },
    { code: "US", timezone: "America/North_Dakota/New_Salem", name: "United States" },
    { code: "GL", timezone: "America/Nuuk", name: "Greenland" },
    { code: "MX", timezone: "America/Ojinaga", name: "Mexico" },
    { code: "PA", timezone: "America/Panama", name: "Panama" },
    { code: "CA", timezone: "America/Pangnirtung", name: "Canada" },
    { code: "SR", timezone: "America/Paramaribo", name: "Suriname" },
    { code: "US", timezone: "America/Phoenix", name: "United States" },
    { code: "HT", timezone: "America/Port-au-Prince", name: "Haiti" },
    { code: "TT", timezone: "America/Port_of_Spain", name: "Trinidad and Tobago" },
    { code: "BR", timezone: "America/Porto_Acre", name: "Brazil" },
    { code: "BR", timezone: "America/Porto_Velho", name: "Brazil" },
    { code: "PR", timezone: "America/Puerto_Rico", name: "Puerto Rico" },
    { code: "CL", timezone: "America/Punta_Arenas", name: "Chile" },
    { code: "CA", timezone: "America/Rainy_River", name: "Canada" },
    { code: "CA", timezone: "America/Rankin_Inlet", name: "Canada" },
    { code: "BR", timezone: "America/Recife", name: "Brazil" },
    { code: "CA", timezone: "America/Regina", name: "Canada" },
    { code: "CA", timezone: "America/Resolute", name: "Canada" },
    { code: "BR", timezone: "America/Rio_Branco", name: "Brazil" },
    { code: "AR", timezone: "America/Rosario", name: "Argentina" },
    { code: "MX", timezone: "America/Santa_Isabel", name: "Mexico" },
    { code: "BR", timezone: "America/Santarem", name: "Brazil" },
    { code: "CL", timezone: "America/Santiago", name: "Chile" },
    { code: "DO", timezone: "America/Santo_Domingo", name: "Dominican Republic" },
    { code: "BR", timezone: "America/Sao_Paulo", name: "Brazil" },
    { code: "GL", timezone: "America/Scoresbysund", name: "Greenland" },
    { code: "US", timezone: "America/Shiprock", name: "United States" },
    { code: "US", timezone: "America/Sitka", name: "United States" },
    { code: "BL", timezone: "America/St_Barthelemy", name: "Saint Barthelemy" },
    { code: "CA", timezone: "America/St_Johns", name: "Canada" },
    { code: "KN", timezone: "America/St_Kitts", name: "Saint Kitts and Nevis" },
    { code: "LC", timezone: "America/St_Lucia", name: "Saint Lucia" },
    { code: "VI", timezone: "America/St_Thomas", name: "U.S. Virgin Islands" },
    { code: "VC", timezone: "America/St_Vincent", name: "Saint Vincent and the Grenadines" },
    { code: "CA", timezone: "America/Swift_Current", name: "Canada" },
    { code: "HN", timezone: "America/Tegucigalpa", name: "Honduras" },
    { code: "GL", timezone: "America/Thule", name: "Greenland" },
    { code: "CA", timezone: "America/Thunder_Bay", name: "Canada" },
    { code: "MX", timezone: "America/Tijuana", name: "Mexico" },
    { code: "CA", timezone: "America/Toronto", name: "Canada" },
    { code: "VG", timezone: "America/Tortola", name: "British Virgin Islands" },
    { code: "CA", timezone: "America/Vancouver", name: "Canada" },
    { code: "VI", timezone: "America/Virgin", name: "U.S. Virgin Islands" },
    { code: "CA", timezone: "America/Whitehorse", name: "Canada" },
    { code: "CA", timezone: "America/Winnipeg", name: "Canada" },
    { code: "US", timezone: "America/Yakutat", name: "United States" },
    { code: "CA", timezone: "America/Yellowknife", name: "Canada" },
    { code: "AQ", timezone: "Antarctica/Casey", name: "Antarctica" },
    { code: "AQ", timezone: "Antarctica/Davis", name: "Antarctica" },
    { code: "AQ", timezone: "Antarctica/DumontDUrville", name: "Antarctica" },
    { code: "AU", timezone: "Antarctica/Macquarie", name: "Australia" },
    { code: "AQ", timezone: "Antarctica/Mawson", name: "Antarctica" },
    { code: "AQ", timezone: "Antarctica/McMurdo", name: "Antarctica" },
    { code: "AQ", timezone: "Antarctica/Palmer", name: "Antarctica" },
    { code: "AQ", timezone: "Antarctica/Rothera", name: "Antarctica" },
    { code: "AQ", timezone: "Antarctica/South_Pole", name: "Antarctica" },
    { code: "AQ", timezone: "Antarctica/Syowa", name: "Antarctica" },
    { code: "AQ", timezone: "Antarctica/Troll", name: "Antarctica" },
    { code: "AQ", timezone: "Antarctica/Vostok", name: "Antarctica" },
    { code: "SJ", timezone: "Arctic/Longyearbyen", name: "Svalbard and Jan Mayen" },
    { code: "YE", timezone: "Asia/Aden", name: "Yemen" },
    { code: "KZ", timezone: "Asia/Almaty", name: "Kazakhstan" },
    { code: "JO", timezone: "Asia/Amman", name: "Jordan" },
    { code: "RU", timezone: "Asia/Anadyr", name: "Russia" },
    { code: "KZ", timezone: "Asia/Aqtau", name: "Kazakhstan" },
    { code: "KZ", timezone: "Asia/Aqtobe", name: "Kazakhstan" },
    { code: "TM", timezone: "Asia/Ashgabat", name: "Turkmenistan" },
    { code: "TM", timezone: "Asia/Ashkhabad", name: "Turkmenistan" },
    { code: "KZ", timezone: "Asia/Atyrau", name: "Kazakhstan" },
    { code: "IQ", timezone: "Asia/Baghdad", name: "Iraq" },
    { code: "BH", timezone: "Asia/Bahrain", name: "Bahrain" },
    { code: "AZ", timezone: "Asia/Baku", name: "Azerbaijan" },
    { code: "TH", timezone: "Asia/Bangkok", name: "Thailand" },
    { code: "RU", timezone: "Asia/Barnaul", name: "Russia" },
    { code: "LB", timezone: "Asia/Beirut", name: "Lebanon" },
    { code: "KG", timezone: "Asia/Bishkek", name: "Kyrgyzstan" },
    { code: "BN", timezone: "Asia/Brunei", name: "Brunei" },
    { code: "IN", timezone: "Asia/Calcutta", name: "India" },
    { code: "RU", timezone: "Asia/Chita", name: "Russia" },
    { code: "MN", timezone: "Asia/Choibalsan", name: "Mongolia" },
    { code: "CN", timezone: "Asia/Chongqing", name: "China" },
    { code: "CN", timezone: "Asia/Chungking", name: "China" },
    { code: "LK", timezone: "Asia/Colombo", name: "Sri Lanka" },
    { code: "BD", timezone: "Asia/Dacca", name: "Bangladesh" },
    { code: "SY", timezone: "Asia/Damascus", name: "Syria" },
    { code: "BD", timezone: "Asia/Dhaka", name: "Bangladesh" },
    { code: "TL", timezone: "Asia/Dili", name: "East Timor" },
    { code: "AE", timezone: "Asia/Dubai", name: "United Arab Emirates" },
    { code: "TJ", timezone: "Asia/Dushanbe", name: "Tajikistan" },
    { code: "CY", timezone: "Asia/Famagusta", name: "Cyprus" },
    { code: "PS", timezone: "Asia/Gaza", name: "Palestine" },
    { code: "CN", timezone: "Asia/Harbin", name: "China" },
    { code: "PS", timezone: "Asia/Hebron", name: "Palestine" },
    { code: "VN", timezone: "Asia/Ho_Chi_Minh", name: "Vietnam" },
    { code: "HK", timezone: "Asia/Hong_Kong", name: "Hong Kong" },
    { code: "MN", timezone: "Asia/Hovd", name: "Mongolia" },
    { code: "RU", timezone: "Asia/Irkutsk", name: "Russia" },
    { code: "TR", timezone: "Asia/Istanbul", name: "Turkey" },
    { code: "ID", timezone: "Asia/Jakarta", name: "Indonesia" },
    { code: "ID", timezone: "Asia/Jayapura", name: "Indonesia" },
    { code: "IL", timezone: "Asia/Jerusalem", name: "Israel" },
    { code: "AF", timezone: "Asia/Kabul", name: "Afghanistan" },
    { code: "RU", timezone: "Asia/Kamchatka", name: "Russia" },
    { code: "PK", timezone: "Asia/Karachi", name: "Pakistan" },
    { code: "CN", timezone: "Asia/Kashgar", name: "China" },
    { code: "NP", timezone: "Asia/Kathmandu", name: "Nepal" },
    { code: "NP", timezone: "Asia/Katmandu", name: "Nepal" },
    { code: "RU", timezone: "Asia/Khandyga", name: "Russia" },
    { code: "IN", timezone: "Asia/Kolkata", name: "India" },
    { code: "RU", timezone: "Asia/Krasnoyarsk", name: "Russia" },
    { code: "MY", timezone: "Asia/Kuala_Lumpur", name: "Malaysia" },
    { code: "MY", timezone: "Asia/Kuching", name: "Malaysia" },
    { code: "KW", timezone: "Asia/Kuwait", name: "Kuwait" },
    { code: "MO", timezone: "Asia/Macao", name: "Macau" },
    { code: "MO", timezone: "Asia/Macau", name: "Macau" },
    { code: "RU", timezone: "Asia/Magadan", name: "Russia" },
    { code: "ID", timezone: "Asia/Makassar", name: "Indonesia" },
    { code: "PH", timezone: "Asia/Manila", name: "Philippines" },
    { code: "OM", timezone: "Asia/Muscat", name: "Oman" },
    { code: "CY", timezone: "Asia/Nicosia", name: "Cyprus" },
    { code: "RU", timezone: "Asia/Novokuznetsk", name: "Russia" },
    { code: "RU", timezone: "Asia/Novosibirsk", name: "Russia" },
    { code: "RU", timezone: "Asia/Omsk", name: "Russia" },
    { code: "KZ", timezone: "Asia/Oral", name: "Kazakhstan" },
    { code: "KH", timezone: "Asia/Phnom_Penh", name: "Cambodia" },
    { code: "ID", timezone: "Asia/Pontianak", name: "Indonesia" },
    { code: "KP", timezone: "Asia/Pyongyang", name: "North Korea" },
    { code: "QA", timezone: "Asia/Qatar", name: "Qatar" },
    { code: "KZ", timezone: "Asia/Qostanay", name: "Kazakhstan" },
    { code: "KZ", timezone: "Asia/Qyzylorda", name: "Kazakhstan" },
    { code: "MM", timezone: "Asia/Rangoon", name: "Myanmar" },
    { code: "SA", timezone: "Asia/Riyadh", name: "Saudi Arabia" },
    { code: "VN", timezone: "Asia/Saigon", name: "Vietnam" },
    { code: "RU", timezone: "Asia/Sakhalin", name: "Russia" },
    { code: "UZ", timezone: "Asia/Samarkand", name: "Uzbekistan" },
    { code: "KR", timezone: "Asia/Seoul", name: "South Korea" },
    { code: "CN", timezone: "Asia/Shanghai", name: "China" },
    { code: "SG", timezone: "Asia/Singapore", name: "Singapore" },
    { code: "RU", timezone: "Asia/Srednekolymsk", name: "Russia" },
    { code: "TW", timezone: "Asia/Taipei", name: "Taiwan" },
    { code: "UZ", timezone: "Asia/Tashkent", name: "Uzbekistan" },
    { code: "GE", timezone: "Asia/Tbilisi", name: "Georgia" },
    { code: "IR", timezone: "Asia/Tehran", name: "Iran" },
    { code: "IL", timezone: "Asia/Tel_Aviv", name: "Israel" },
    { code: "BT", timezone: "Asia/Thimbu", name: "Bhutan" },
    { code: "BT", timezone: "Asia/Thimphu", name: "Bhutan" },
    { code: "JP", timezone: "Asia/Tokyo", name: "Japan" },
    { code: "RU", timezone: "Asia/Tomsk", name: "Russia" },
    { code: "ID", timezone: "Asia/Ujung_Pandang", name: "Indonesia" },
    { code: "MN", timezone: "Asia/Ulaanbaatar", name: "Mongolia" },
    { code: "MN", timezone: "Asia/Ulan_Bator", name: "Mongolia" },
    { code: "CN", timezone: "Asia/Urumqi", name: "China" },
    { code: "RU", timezone: "Asia/Ust-Nera", name: "Russia" },
    { code: "LA", timezone: "Asia/Vientiane", name: "Laos" },
    { code: "RU", timezone: "Asia/Vladivostok", name: "Russia" },
    { code: "RU", timezone: "Asia/Yakutsk", name: "Russia" },
    { code: "MM", timezone: "Asia/Yangon", name: "Myanmar" },
    { code: "RU", timezone: "Asia/Yekaterinburg", name: "Russia" },
    { code: "AM", timezone: "Asia/Yerevan", name: "Armenia" },
    { code: "PT", timezone: "Atlantic/Azores", name: "Portugal" },
    { code: "BM", timezone: "Atlantic/Bermuda", name: "Bermuda" },
    { code: "ES", timezone: "Atlantic/Canary", name: "Spain" },
    { code: "CV", timezone: "Atlantic/Cape_Verde", name: "Cape Verde" },
    { code: "FO", timezone: "Atlantic/Faeroe", name: "Faroe Islands" },
    { code: "FO", timezone: "Atlantic/Faroe", name: "Faroe Islands" },
    { code: "SJ", timezone: "Atlantic/Jan_Mayen", name: "Svalbard and Jan Mayen" },
    { code: "PT", timezone: "Atlantic/Madeira", name: "Portugal" },
    { code: "IS", timezone: "Atlantic/Reykjavik", name: "Iceland" },
    { code: "GS", timezone: "Atlantic/South_Georgia", name: "South Georgia/South Sandwich Islands" },
    { code: "SH", timezone: "Atlantic/St_Helena", name: "Saint Helena" },
    { code: "FK", timezone: "Atlantic/Stanley", name: "Falkland Islands" },
    { code: "AU", timezone: "Australia/ACT", name: "Australia" },
    { code: "AU", timezone: "Australia/Adelaide", name: "Australia" },
    { code: "AU", timezone: "Australia/Brisbane", name: "Australia" },
    { code: "AU", timezone: "Australia/Broken_Hill", name: "Australia" },
    { code: "AU", timezone: "Australia/Canberra", name: "Australia" },
    { code: "AU", timezone: "Australia/Currie", name: "Australia" },
    { code: "AU", timezone: "Australia/Darwin", name: "Australia" },
    { code: "AU", timezone: "Australia/Eucla", name: "Australia" },
    { code: "AU", timezone: "Australia/Hobart", name: "Australia" },
    { code: "AU", timezone: "Australia/LHI", name: "Australia" },
    { code: "AU", timezone: "Australia/Lindeman", name: "Australia" },
    { code: "AU", timezone: "Australia/Lord_Howe", name: "Australia" },
    { code: "AU", timezone: "Australia/Melbourne", name: "Australia" },
    { code: "AU", timezone: "Australia/North", name: "Australia" },
    { code: "AU", timezone: "Australia/NSW", name: "Australia" },
    { code: "AU", timezone: "Australia/Perth", name: "Australia" },
    { code: "AU", timezone: "Australia/Queensland", name: "Australia" },
    { code: "AU", timezone: "Australia/South", name: "Australia" },
    { code: "AU", timezone: "Australia/Sydney", name: "Australia" },
    { code: "AU", timezone: "Australia/Tasmania", name: "Australia" },
    { code: "AU", timezone: "Australia/Victoria", name: "Australia" },
    { code: "AU", timezone: "Australia/West", name: "Australia" },
    { code: "AU", timezone: "Australia/Yancowinna", name: "Australia" },
    { code: "BR", timezone: "Brazil/Acre", name: "Brazil" },
    { code: "BR", timezone: "Brazil/DeNoronha", name: "Brazil" },
    { code: "BR", timezone: "Brazil/East", name: "Brazil" },
    { code: "BR", timezone: "Brazil/West", name: "Brazil" },
    { code: "CA", timezone: "Canada/Atlantic", name: "Canada" },
    { code: "CA", timezone: "Canada/Central", name: "Canada" },
    { code: "CA", timezone: "Canada/Eastern", name: "Canada" },
    { code: "CA", timezone: "Canada/Mountain", name: "Canada" },
    { code: "CA", timezone: "Canada/Newfoundland", name: "Canada" },
    { code: "CA", timezone: "Canada/Pacific", name: "Canada" },
    { code: "CA", timezone: "Canada/Saskatchewan", name: "Canada" },
    { code: "CA", timezone: "Canada/Yukon", name: "Canada" },
    { code: "CL", timezone: "Chile/Continental", name: "Chile" },
    { code: "CL", timezone: "Chile/EasterIsland", name: "Chile" },
    { code: "CU", timezone: "Cuba", name: "Cuba" },
    { code: "EG", timezone: "Egypt", name: "Egypt" },
    { code: "IE", timezone: "Eire", name: "Ireland" },
    { code: "NL", timezone: "Europe/Amsterdam", name: "Netherlands" },
    { code: "AD", timezone: "Europe/Andorra", name: "Andorra" },
    { code: "RU", timezone: "Europe/Astrakhan", name: "Russia" },
    { code: "GR", timezone: "Europe/Athens", name: "Greece" },
    { code: "GB", timezone: "Europe/Belfast", name: "United Kingdom" },
    { code: "RS", timezone: "Europe/Belgrade", name: "Serbia" },
    { code: "DE", timezone: "Europe/Berlin", name: "Germany" },
    { code: "SK", timezone: "Europe/Bratislava", name: "Slovakia" },
    { code: "BE", timezone: "Europe/Brussels", name: "Belgium" },
    { code: "RO", timezone: "Europe/Bucharest", name: "Romania" },
    { code: "HU", timezone: "Europe/Budapest", name: "Hungary" },
    { code: "DE", timezone: "Europe/Busingen", name: "Germany" },
    { code: "MD", timezone: "Europe/Chisinau", name: "Moldova" },
    { code: "DK", timezone: "Europe/Copenhagen", name: "Denmark" },
    { code: "IE", timezone: "Europe/Dublin", name: "Ireland" },
    { code: "GI", timezone: "Europe/Gibraltar", name: "Gibraltar" },
    { code: "GG", timezone: "Europe/Guernsey", name: "Guernsey" },
    { code: "FI", timezone: "Europe/Helsinki", name: "Finland" },
    { code: "IM", timezone: "Europe/Isle_of_Man", name: "Isle of Man" },
    { code: "TR", timezone: "Europe/Istanbul", name: "Turkey" },
    { code: "JE", timezone: "Europe/Jersey", name: "Jersey" },
    { code: "RU", timezone: "Europe/Kaliningrad", name: "Russia" },
    { code: "UA", timezone: "Europe/Kiev", name: "Ukraine" },
    { code: "RU", timezone: "Europe/Kirov", name: "Russia" },
    { code: "PT", timezone: "Europe/Lisbon", name: "Portugal" },
    { code: "SI", timezone: "Europe/Ljubljana", name: "Slovenia" },
    { code: "GB", timezone: "Europe/London", name: "United Kingdom" },
    { code: "LU", timezone: "Europe/Luxembourg", name: "Luxembourg" },
    { code: "ES", timezone: "Europe/Madrid", name: "Spain" },
    { code: "MT", timezone: "Europe/Malta", name: "Malta" },
    { code: "AX", timezone: "Europe/Mariehamn", name: "Åland Islands, Finland" },
    { code: "BY", timezone: "Europe/Minsk", name: "Belarus" },
    { code: "MC", timezone: "Europe/Monaco", name: "Monaco" },
    { code: "RU", timezone: "Europe/Moscow", name: "Russia" },
    { code: "CY", timezone: "Europe/Nicosia", name: "Cyprus" },
    { code: "NO", timezone: "Europe/Oslo", name: "Norway" },
    { code: "FR", timezone: "Europe/Paris", name: "France" },
    { code: "ME", timezone: "Europe/Podgorica", name: "Montenegro" },
    { code: "CZ", timezone: "Europe/Prague", name: "Czech Republic" },
    { code: "LV", timezone: "Europe/Riga", name: "Latvia" },
    { code: "IT", timezone: "Europe/Rome", name: "Italy" },
    { code: "RU", timezone: "Europe/Samara", name: "Russia" },
    { code: "SM", timezone: "Europe/San_Marino", name: "San Marino" },
    { code: "BA", timezone: "Europe/Sarajevo", name: "Bosnia and Herzegovina" },
    { code: "RU", timezone: "Europe/Saratov", name: "Russia" },
    { code: "UA", timezone: "Europe/Simferopol", name: "Ukraine" },
    { code: "MK", timezone: "Europe/Skopje", name: "Macedonia" },
    { code: "BG", timezone: "Europe/Sofia", name: "Bulgaria" },
    { code: "SE", timezone: "Europe/Stockholm", name: "Sweden" },
    { code: "EE", timezone: "Europe/Tallinn", name: "Estonia" },
    { code: "AL", timezone: "Europe/Tirane", name: "Albania" },
    { code: "MD", timezone: "Europe/Tiraspol", name: "Moldova" },
    { code: "RU", timezone: "Europe/Ulyanovsk", name: "Russia" },
    { code: "UA", timezone: "Europe/Uzhgorod", name: "Ukraine" },
    { code: "LI", timezone: "Europe/Vaduz", name: "Liechtenstein" },
    { code: "VA", timezone: "Europe/Vatican", name: "Vatican" },
    { code: "AT", timezone: "Europe/Vienna", name: "Austria" },
    { code: "LT", timezone: "Europe/Vilnius", name: "Lithuania" },
    { code: "RU", timezone: "Europe/Volgograd", name: "Russia" },
    { code: "PL", timezone: "Europe/Warsaw", name: "Poland" },
    { code: "HR", timezone: "Europe/Zagreb", name: "Croatia" },
    { code: "UA", timezone: "Europe/Zaporozhye", name: "Ukraine" },
    { code: "CH", timezone: "Europe/Zurich", name: "Switzerland" },
    { code: "GB", timezone: "GB", name: "United Kingdom" },
    { code: "GB", timezone: "GB-Eire", name: "United Kingdom" },
    { code: "HK", timezone: "Hongkong", name: "Hong Kong" },
    { code: "IS", timezone: "Iceland", name: "Iceland" },
    { code: "MG", timezone: "Indian/Antananarivo", name: "Madagascar" },
    { code: "IO", timezone: "Indian/Chagos", name: "British Indian Ocean Territory" },
    { code: "CX", timezone: "Indian/Christmas", name: "Christmas Island" },
    { code: "CC", timezone: "Indian/Cocos", name: "Cocos Islands" },
    { code: "KM", timezone: "Indian/Comoro", name: "Comoros" },
    { code: "TF", timezone: "Indian/Kerguelen", name: "Kerguelen Islands" },
    { code: "SC", timezone: "Indian/Mahe", name: "Seychelles" },
    { code: "MV", timezone: "Indian/Maldives", name: "Maldives" },
    { code: "MU", timezone: "Indian/Mauritius", name: "Mauritius" },
    { code: "YT", timezone: "Indian/Mayotte", name: "Mayotte" },
    { code: "RE", timezone: "Indian/Reunion", name: "Reunion" },
    { code: "IR", timezone: "Iran", name: "Iran" },
    { code: "IL", timezone: "Israel", name: "Israel" },
    { code: "JM", timezone: "Jamaica", name: "Jamaica" },
    { code: "JP", timezone: "Japan", name: "Japan" },
    { code: "MH", timezone: "Kwajalein", name: "Marshall Islands" },
    { code: "LY", timezone: "Libya", name: "Libya" },
    { code: "MX", timezone: "Mexico/BajaNorte", name: "Mexico" },
    { code: "MX", timezone: "Mexico/BajaSur", name: "Mexico" },
    { code: "MX", timezone: "Mexico/General", name: "Mexico" },
    { code: "US", timezone: "Navajo", name: "United States" },
    { code: "NZ", timezone: "NZ", name: "New Zealand" },
    { code: "NZ", timezone: "NZ-CHAT", name: "New Zealand" },
    { code: "WS", timezone: "Pacific/Apia", name: "Samoa" },
    { code: "NZ", timezone: "Pacific/Auckland", name: "New Zealand" },
    { code: "PG", timezone: "Pacific/Bougainville", name: "Papua New Guinea" },
    { code: "NZ", timezone: "Pacific/Chatham", name: "New Zealand" },
    { code: "FM", timezone: "Pacific/Chuuk", name: "Micronesia" },
    { code: "CL", timezone: "Pacific/Easter", name: "Chile" },
    { code: "VU", timezone: "Pacific/Efate", name: "Vanuatu" },
    { code: "KI", timezone: "Pacific/Enderbury", name: "Kiribati" },
    { code: "TK", timezone: "Pacific/Fakaofo", name: "Tokelau" },
    { code: "FJ", timezone: "Pacific/Fiji", name: "Fiji" },
    { code: "TV", timezone: "Pacific/Funafuti", name: "Tuvalu" },
    { code: "EC", timezone: "Pacific/Galapagos", name: "Ecuador" },
    { code: "PF", timezone: "Pacific/Gambier", name: "French Polynesia" },
    { code: "SB", timezone: "Pacific/Guadalcanal", name: "Solomon Islands" },
    { code: "GU", timezone: "Pacific/Guam", name: "Guam" },
    { code: "US", timezone: "Pacific/Honolulu", name: "United States" },
    { code: "KI", timezone: "Pacific/Kiritimati", name: "Kiribati" },
    { code: "FM", timezone: "Pacific/Kosrae", name: "Micronesia" },
    { code: "MH", timezone: "Pacific/Kwajalein", name: "Marshall Islands" },
    { code: "MH", timezone: "Pacific/Majuro", name: "Marshall Islands" },
    { code: "PF", timezone: "Pacific/Marquesas", name: "French Polynesia" },
    { code: "NR", timezone: "Pacific/Nauru", name: "Nauru" },
    { code: "NU", timezone: "Pacific/Niue", name: "Niue" },
    { code: "NC", timezone: "Pacific/Noumea", name: "New Caledonia" },
    { code: "AS", timezone: "Pacific/Pago_Pago", name: "American Samoa" },
    { code: "PW", timezone: "Pacific/Palau", name: "Palau" },
    { code: "PN", timezone: "Pacific/Pitcairn", name: "Pitcairn" },
    { code: "FM", timezone: "Pacific/Pohnpei", name: "Micronesia" },
    { code: "FM", timezone: "Pacific/Ponape", name: "Micronesia" },
    { code: "PG", timezone: "Pacific/Port_Moresby", name: "Papua New Guinea" },
    { code: "CK", timezone: "Pacific/Rarotonga", name: "Cook Islands" },
    { code: "MP", timezone: "Pacific/Saipan", name: "Northern Mariana Islands" },
    { code: "WS", timezone: "Pacific/Samoa", name: "Samoa" },
    { code: "PF", timezone: "Pacific/Tahiti", name: "French Polynesia" },
    { code: "KI", timezone: "Pacific/Tarawa", name: "Kiribati" },
    { code: "TO", timezone: "Pacific/Tongatapu", name: "Tonga" },
    { code: "FM", timezone: "Pacific/Truk", name: "Micronesia" },
    { code: "WF", timezone: "Pacific/Wallis", name: "Wallis and Futuna" },
    { code: "FM", timezone: "Pacific/Yap", name: "Micronesia" },
    { code: "PL", timezone: "Poland", name: "Poland" },
    { code: "PT", timezone: "Portugal", name: "Portugal" },
    { code: "CN", timezone: "PRC", name: "China" },
    { code: "TW", timezone: "ROC", name: "Taiwan" },
    { code: "KR", timezone: "ROK", name: "South Korea" },
    { code: "SG", timezone: "Singapore", name: "Singapore" },
    { code: "TR", timezone: "Turkey", name: "Turkey" },
    { code: "US", timezone: "US/Alaska", name: "United States" },
    { code: "US", timezone: "US/Aleutian", name: "United States" },
    { code: "US", timezone: "US/Arizona", name: "United States" },
    { code: "US", timezone: "US/Central", name: "United States" },
    { code: "US", timezone: "US/East-Indiana", name: "United States" },
    { code: "US", timezone: "US/Eastern", name: "United States" },
    { code: "US", timezone: "US/Hawaii", name: "United States" },
    { code: "US", timezone: "US/Indiana-Starke", name: "United States" },
    { code: "US", timezone: "US/Michigan", name: "United States" },
    { code: "US", timezone: "US/Mountain", name: "United States" },
    { code: "US", timezone: "US/Pacific", name: "United States" },
    { code: "WS", timezone: "US/Samoa", name: "Samoa" },
    { code: "RU", timezone: "W-SU", name: "Russia" },
];

const find = (value: string, search: "code" | "timezone" | "name", result: "code" | "timezone" | "name") => {
    const [match] = countries.filter(i => lowerCase(i[search]) == lowerCase(value));
    return (match && result in match) ? match[result] : null;
};

export const countryNameFromTimeZone = (tz: string) => find(tz,"timezone","name");
export const countryCodeFromTimeZone = (tz: string) => find(tz,"timezone","code");
export const countryNameFromCode = (code: string) => find(code,"code","name");
export const countryCodeFromName = (name: string) => find(name,"name","code");